import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

// Author/creator: nattapat2871 (https://nattapat2871.me)

const mainSource = await (await import('./sourceText.mjs')).readElectronMainSource()
const preloadSource = await readFile(new URL('../electron/preload.ts', import.meta.url), 'utf8')
const appSource = await (await import('./sourceText.mjs')).readRendererAppSource()
const viteConfig = await readFile(new URL('../vite.config.ts', import.meta.url), 'utf8')

test('content install tasks can be cancelled from the renderer', () => {
  assert.match(mainSource, /const activeInstallTasks = new Map<string, InstallTask>\(\)/)
  assert.match(mainSource, /trustedIpcHandle\('cancel-install-task'/)
  assert.match(mainSource, /AbortController/)
  assert.match(mainSource, /downloadFile[\s\S]*signal\?: AbortSignal/)
  assert.match(preloadSource, /cancelInstallTask: \(taskId: string\) => invoke\('cancel-install-task'/)
  assert.match(appSource, /const cancelActiveInstall =/)
  assert.match(appSource, /installingCurrentModpack[\s\S]*cancelActiveInstall\(\)/)
  assert.match(appSource, /installLocalMrpack\(\{ taskId \}\)/)
})

test('launcher error reports use the public ingest contract without exposing admin audit', () => {
  assert.match(mainSource, /INJECTED_ERROR_REPORT_TOKEN/)
  assert.match(mainSource, /INJECTED_ERROR_REPORT_TOKEN \|\| String\(process\.env\.NAMLAUNCHER_ERROR_REPORT_TOKEN/)
  assert.match(mainSource, /getErrorReportSubmitFailureMessage/)
  assert.match(mainSource, /ERROR_REPORT_MESSAGE_MAX_LENGTH = 12000/)
  assert.match(mainSource, /ERROR_REPORT_LOGS_MAX_LENGTH = 220000/)
  assert.match(mainSource, /const reportMessage = diagnosis \? `\$\{diagnosis\}\\n\\n\$\{report\.message\}` : report\.message/)
  assert.match(mainSource, /truncateRemoteText\(reportMessage, ERROR_REPORT_MESSAGE_MAX_LENGTH\)/)
  assert.match(mainSource, /truncateRemoteText\(report\.logs, ERROR_REPORT_LOGS_MAX_LENGTH\)/)
  assert.match(mainSource, /const normalizeErrorReportPlayerName = \(value: unknown\) =>/)
  assert.match(mainSource, /const playerName = normalizeErrorReportPlayerName\(request\.playerName \|\| report\.playerName \|\| account\?\.name \|\| 'unknown'\)/)
  assert.match(mainSource, /let activeErrorReportAccountId: string \| null = null/)
  assert.match(mainSource, /const defaultAccount = getDefaultErrorReportAccount\(\)/)
  assert.match(mainSource, /playerName: normalizeErrorReportPlayerName\(metadata\.playerName \|\| defaultAccount\?\.name \|\| 'unknown'\)/)
  assert.match(mainSource, /accountType: trimRemoteText\(metadata\.accountType \|\| defaultAccount\?\.type \|\| '', 24\) \|\| null/)
  assert.match(mainSource, /trustedIpcHandle\('set-active-account-context'/)
  assert.match(preloadSource, /setActiveAccountContext: \(accountId: string \| null\) => invoke\('set-active-account-context', accountId\)/)
  assert.match(appSource, /window\.electron\.setActiveAccountContext\(activeAccountId\)/)
  assert.doesNotMatch(mainSource, /sanitizeBugReport\(String\(request\.playerName \|\| account\?\.name \|\| 'unknown'\)\)/)
  assert.match(mainSource, /const getCompactErrorLog = \(err: unknown\) =>/)
  assert.match(mainSource, /log\.debug\('Online heartbeat failed\.', getCompactErrorLog\(err\)\)/)
  assert.match(mainSource, /log\.debug\('Launcher website stats check failed', getCompactErrorLog\(err\)\)/)
  assert.doesNotMatch(mainSource, /log\.debug\('Online heartbeat failed\.', err\)/)
  assert.match(mainSource, /status === 422/)
  assert.match(viteConfig, /NAMLAUNCHER_ERROR_REPORT_TOKEN/)
  assert.match(mainSource, /Authorization: `Bearer \$\{ERROR_REPORT_TOKEN\}`/)
  assert.match(mainSource, /requestStatsApiJson\('\/api\/error-reports'/)
  assert.match(mainSource, /net\.fetch\(url/)
  assert.match(mainSource, /timeout: 45000/)
  assert.match(mainSource, /const discordQueued = Boolean\(response\.discord_queued\)/)
  assert.match(mainSource, /const duplicate = Boolean\(response\.duplicate\)/)
  assert.match(mainSource, /const occurrenceCount = Math\.max\(1, Number\(response\.occurrence_count\) \|\| 1\)/)
  assert.match(mainSource, /submission_mode: submissionMode/)
  assert.match(mainSource, /const automaticLauncherErrorSubmissions = new Map/)
  assert.match(mainSource, /pendingAutomaticSubmission[\s\S]*await pendingAutomaticSubmission/)
  assert.match(mainSource, /submitLauncherErrorReport\(\{[\s\S]*reportId: report\.id[\s\S]*\}, 'automatic'\)/)
  assert.match(mainSource, /const confirmLauncherErrorReport = async/)
  assert.match(mainSource, /error-reports\/\$\{encodeURIComponent\(canonicalReportId\)\}\/confirm/)
  assert.match(mainSource, /confirmation: 'occurred'/)
  assert.match(mainSource, /discordDispatched: Boolean\(response\.discord_dispatched\)/)
  assert.match(mainSource, /discordQueued: Boolean\(response\.discord_queued\)/)
  assert.match(mainSource, /if \(!duplicate && !discordDispatched && !discordQueued\)/)
  assert.match(preloadSource, /submitErrorReport: \(request: any\) => invoke\('submit-error-report'/)
  assert.match(appSource, /submitLauncherErrorReport/)
  assert.match(appSource, /if \(!result\.confirmed\)/)
  assert.match(appSource, /if \(!result\.discordDispatched\)/)
  assert.match(appSource, /launcherError\.submit\.pending/)
  assert.match(appSource, /errorSubmitDetail/)
  assert.match(appSource, /submittedErrorReportsRef\.current\.add\(launcherErrorReport\.id\)/)
  assert.match(appSource, /disabled=\{errorSubmitState === 'sending' \|\| errorSubmitState === 'sent'/)
  assert.doesNotMatch(mainSource, /error-reports\/audit|auditLauncherErrorReportDispatch|audit-error-report-dispatch/)
  assert.doesNotMatch(preloadSource, /auditErrorReportDispatch|audit-error-report-dispatch/)
  assert.doesNotMatch(appSource, /auditErrorReportDispatch|auditLauncherErrorDispatch/)
})
